/**
 * Builds public/js/site-config.js from environment variables.
 * Used locally and on Vercel so contact/links stay configurable.
 */
const fs = require('fs');
const path = require('path');

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  const text = fs.readFileSync(filePath, 'utf8');
  text.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eq = trimmed.indexOf('=');
    if (eq === -1) return;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  });
}

loadEnvFile(path.join(__dirname, '..', '.env'));

const config = {
  siteUrl: process.env.SITE_URL || 'https://le-petit-oiseau.vercel.app',
  phone: process.env.PHONE || '+233599420024',
  phoneDisplay: process.env.PHONE_DISPLAY || '+233 59 942 0024',
  whatsappUrl: process.env.WHATSAPP_URL || 'https://wa.me/233599420024',
  instagramUrl: process.env.INSTAGRAM_URL || 'https://www.instagram.com/lepetitoiseaugh/',
  menuUrl: process.env.MENU_URL || 'https://bit.ly/LepetitOiseaughmenu',
  supperClubUrl: process.env.SUPPER_CLUB_URL || 'https://www.instagram.com/lepetitoiseaugh/',
  mapsUrl: process.env.MAPS_URL || 'https://maps.google.com/?q=Le+Petit+Oiseau+Accra+HR6H%2BFG6',
  mapsEmbedUrl:
    process.env.MAPS_EMBED_URL ||
    'https://maps.google.com/maps?q=HR6H%2BFG6,Accra,Ghana&z=16&output=embed',
  locationLine: process.env.LOCATION_LINE || 'Nyaniba-Labone, Accra',
  locationDetail: process.env.LOCATION_DETAIL || 'Behind Alley Bar',
  hours: process.env.HOURS || '12:00 – 23:00, daily',
  siteName: process.env.SITE_NAME || 'Le Petit Oiseau',
  siteTagline: process.env.SITE_TAGLINE || 'Afro-Fusion × French',
  metaDescription:
    process.env.META_DESCRIPTION ||
    'Le Petit Oiseau — Afro-Fusion × French dining in Nyaniba-Labone, Accra.'
};

const outDir = path.join(__dirname, '..', 'public', 'js');
fs.mkdirSync(outDir, { recursive: true });

const outFile = path.join(outDir, 'site-config.js');
const body = `/* Generated by scripts/build-config.js — do not edit by hand */
window.SITE_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync(outFile, body, 'utf8');
console.log('Wrote', outFile);
